# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 23:34
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblogpage',
            name='cover',
            field=mezzanine.core.fields.FileField(max_length=255, verbose_name='Image'),
        ),
    ]
